AWSTemplateFormatVersion: "2010-09-09"

Description: EC2 simple template

# MyMetaParameters:
#   stack: simple
#   region: us-east-1

Parameters:

  ParamAMI:
    Type: String
    Default: ami-0ff8a91507f77f867
    Description: "AMI: Virginia"

  ParamKeyName:
    Type: String
    Default: testkey

  ParamInstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.nano
      - t2.micro
      - t3.nano
      - t3.micro
    Description: t[23].{nano,micro}

Resources:

  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !Ref ParamAMI
      KeyName: !Ref ParamKeyName
      InstanceType: !Ref ParamInstanceType
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sdm
          Ebs:
            VolumeType: gp2
            VolumeSize: 20
            DeleteOnTermination: false

  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyEC2Instance

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - { "IpProtocol": "tcp", "FromPort": "22", "ToPort": "22", "CidrIp": "0.0.0.0/0" }
        - { "IpProtocol": "tcp", "FromPort": "80", "ToPort": "80", "CidrIp": "0.0.0.0/0" }


Outputs:

  InstanceEIP:
    Description: Instance Elastic IP
    Value: !Ref MyEIP
    Export:
      Name: !Sub "${AWS::StackName}-EIP"

  InstancePrivIP:
    Description: Instance Private IP
    Value: !GetAtt MyEC2Instance.PrivateIp

  InstanceId:
    Description: Instance Id
    Value: !Ref MyEC2Instance


